services:
  faster-whisper-server-cuda:
    image: crpi-ljf6ob20bt5kluhe.cn-shanghai.personal.cr.aliyuncs.com/voicelinkvr/faster-whisper-server:latest-cpu
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - hugging_face_cache:/root/.cache/huggingface:rw
    develop:
      watch:
        - path: faster_whisper_server
          action: rebuild

  libretranslate:
    image: crpi-ljf6ob20bt5kluhe.cn-shanghai.personal.cr.aliyuncs.com/voicelinkvr/libretranslate
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      # Keep the models in a docker volume, to avoid re-downloading on startup
      - lt-local:/home/libretranslate/.local:rw
    ## Uncomment above command and define your args if necessary
    # command: --ssl --ga-id MY-GA-ID --req-limit 100 --char-limit 500
    ## Uncomment this section and the libretranslate_api_keys volume if you want to backup your API keys
    # environment:
    #   - LT_API_KEYS=true
    #   - LT_API_KEYS_DB_PATH=/app/db/api_keys.db # Same result as `db/api_keys.db` or `./db/api_keys.db`
    ## Uncomment these vars and libretranslate_models volume to optimize loading time.
    #   - LT_UPDATE_MODELS=true
    #   - LT_LOAD_ONLY=en,fr
    # volumes:
    #   - libretranslate_api_keys:/app/db

  VoiceLinkVR-server:
    image: crpi-ljf6ob20bt5kluhe.cn-shanghai.personal.cr.aliyuncs.com/voicelinkvr/voice-link-vr-server:latest
    restart: unless-stopped
    ports:
      - 8980:8980
    volumes:
      -  voice-link-vr-server-local:/usr/src/app/data:rw
    
volumes:
  lt-local:
  hugging_face_cache:
  voice-link-vr-server-local: