services:
  redis:
    image: crpi-ljf6ob20bt5kluhe.cn-shanghai.personal.cr.aliyuncs.com/voicelinkvr/redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redisFiles/data:/data
      - ./redisFiles/redis.conf:/usr/local/etc/redis/redis.conf
      # - ./redisFiles/logs:/logs
    #配置文件启动
    command: redis-server /usr/local/etc/redis/redis.conf
  faster-whisper-server-cuda:
    image: crpi-ljf6ob20bt5kluhe.cn-shanghai.personal.cr.aliyuncs.com/voicelinkvr/faster-whisper-server:latest-cuda
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - WHISPER__TTL=-1
      - WHISPER__NUM_WORKERS=10
      - WHISPER__CPU_THREADS=40
       # environment params in:https://github.com/speaches-ai/speaches/blob/v0.5.0/src/faster_whisper_server/config.py
    deploy:
      resources:
        reservations:
          devices:
            - count: all
              driver: nvidia
              capabilities: [gpu]
              

  libretranslate-cuda:
    # image: libretranslate/libretranslate
    image: crpi-ljf6ob20bt5kluhe.cn-shanghai.personal.cr.aliyuncs.com/voicelinkvr/libretranslate:latest-cuda
    restart: unless-stopped
    ports:
      - 5000:5000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # volumes:
      # Keep the models in a docker volume, to avoid re-downloading on startup
      # - lt-local:/home/libretranslate/.local:rw
    ## Uncomment above command and define your args if necessary
    # command: --ssl --ga-id MY-GA-ID --req-limit 100 --char-limit 500
    ## Uncomment this section and the libretranslate_api_keys volume if you want to backup your API keys
    environment:
      - LT_THREADS=20
    #   - LT_API_KEYS=true
    #   - LT_API_KEYS_DB_PATH=/app/db/api_keys.db # Same result as `db/api_keys.db` or `./db/api_keys.db`
    ## Uncomment these vars and libretranslate_models volume to optimize loading time.
    #   - LT_UPDATE_MODELS=true
    #   - LT_LOAD_ONLY=en,fr
    # volumes:
    #   - libretranslate_api_keys:/app/db
  sensevoice:
    # image: registry.cn-hangzhou.aliyuncs.com/lucklittleboy/sensevoice-oneapi:1.0
    image: crpi-ljf6ob20bt5kluhe.cn-shanghai.personal.cr.aliyuncs.com/voicelinkvr/sensevoice-oneapi:latest
    restart: unless-stopped
    ports:
      - 8800:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - DEVICE_TYPE=cuda:0
      - use_itn=True
      - ncpu=8
      - VAD_ENABLE=False

  # VoiceLinkVR-server-2:
  #   image: crpi-ljf6ob20bt5kluhe.cn-shanghai.personal.cr.aliyuncs.com/voicelinkvr/voice-link-vr-server:v1.8
  #   restart: unless-stopped
  #   ports:
  #     - 8981:8980
  #   volumes:
  #     - voice-link-vr-server-local:/usr/src/app/data:rw
  #   environment:
  #     - SENSEVOICE_HOST=sensevoice
  #     - SENSEVOICE_PORT=8000
  #     - WHISPER_HOST=faster-whisper-server-cuda
  #     - WHISPER_PORT=8000
  #     - LIBRETRANSLATE_HOST=libretranslate-cuda
  #     - LIBRETRANSLATE_PORT=5000
  #     - FILTER_WEB_URL=https://gitee.com/voice-link-vr/VoiceLinkServer/raw/main/src/filter.json
  #     - THREADS_NUM=50
  #     - LIMIT_ENABLE=True
  #     - LIMIT_PUBLIC_TEST_USER=testuser
  #     - SQLALCHEMY_POOL_SIZE=0
  #     - TRANSLATOR_SERVICE=bing
  #     - LIMITER_REDIS_URL=redis://redis:6379/0
  #     - TTS_TOKEN=NfuWNpnr64KWB0KHyMRejWbS0wiMujyvJ9t4caaxPTKvPc5PSM
  #     - TTS_URL=https://tts-test.boyqiu001.top/v1/audio/speech
  #     - ENABLE_WEB_TRANSLATORS=True
  #     - LATEST_VERSION=v0.5.2
  #     - PACKAGE_BASE_URL=https://cloudflarestorage.boyqiu001.top/VRCLS-windwos-
  #   depends_on:
  #     - libretranslate-cuda
  #     - faster-whisper-server-cuda
  #     - redis
  VoiceLinkVR-server:
    # image: voice-link-vr-server-test1
    image: crpi-ljf6ob20bt5kluhe.cn-shanghai.personal.cr.aliyuncs.com/voicelinkvr/voice-link-vr-server:latest
    restart: unless-stopped
    ports:
      - 8980:8980
    volumes:
      - voice-link-vr-server-local:/usr/src/app/data:rw
    environment:
      - SENSEVOICE_HOST=sensevoice
      - SENSEVOICE_PORT=8000
      - WHISPER_HOST=faster-whisper-server-cuda
      - WHISPER_PORT=8000
      - LIBRETRANSLATE_HOST=libretranslate-cuda
      - LIBRETRANSLATE_PORT=5000
      - FILTER_WEB_URL=https://gitee.com/voice-link-vr/VoiceLinkServer/raw/main/src/filter.json
      - THREADS_NUM=50
      - LIMIT_ENABLE=True
      - LIMIT_PUBLIC_TEST_USER=testuser
      - SQLALCHEMY_POOL_SIZE=0
      - TRANSLATOR_SERVICE=bing
      - LIMITER_REDIS_URL=redis://redis:6379/0
      - TTS_TOKEN=
      - TTS_URL=
      - ENABLE_WEB_TRANSLATORS=True
      - LATEST_VERSION=v0.6.0-fix1
      - PACKAGE_BASE_URL=https://cloudflarestorage.boyqiu001.top/VRCLS-windows-
      - PACKAGE_TYPE=.exe
      # 可以使用mysql
      # - SQL_PATH=mysql+pymysql://voicelinkvr:voicelinkabc123%40@192.168.2.198:3306/voicelinkvr_server_test?charset=utf8
    depends_on:
      - sensevoice
      - libretranslate-cuda
      - faster-whisper-server-cuda
      - redis
volumes:
  voice-link-vr-server-local: