services:
  faster-whisper-server-cuda:
    image: crpi-ljf6ob20bt5kluhe.cn-shanghai.personal.cr.aliyuncs.com/voicelinkvr/faster-whisper-server:latest-cuda
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - WHISPER__TTL=-1
       # environment params in:https://github.com/speaches-ai/speaches/blob/v0.5.0/src/faster_whisper_server/config.py
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              driver: nvidia

  libretranslate-cuda:
    # image: libretranslate/libretranslate
    image: crpi-ljf6ob20bt5kluhe.cn-shanghai.personal.cr.aliyuncs.com/voicelinkvr/libretranslate:latest-cuda
    restart: unless-stopped
    ports:
      - 5000:5000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

    # volumes:
      # Keep the models in a docker volume, to avoid re-downloading on startup
      # - lt-local:/home/libretranslate/.local:rw
    ## Uncomment above command and define your args if necessary
    # command: --ssl --ga-id MY-GA-ID --req-limit 100 --char-limit 500
    ## Uncomment this section and the libretranslate_api_keys volume if you want to backup your API keys
    # environment:
    #   - LT_THREADS=10
    #   - LT_API_KEYS=true
    #   - LT_API_KEYS_DB_PATH=/app/db/api_keys.db # Same result as `db/api_keys.db` or `./db/api_keys.db`
    ## Uncomment these vars and libretranslate_models volume to optimize loading time.
    #   - LT_UPDATE_MODELS=true
    #   - LT_LOAD_ONLY=en,fr
    # volumes:
    #   - libretranslate_api_keys:/app/db

  VoiceLinkVR-server-test:
    image: voice-link-vr-server
    restart: unless-stopped
    ports:
      - 8980:8980
    volumes:
      - voice-link-vr-server-local:/usr/src/app/data:rw
    environment:
      - WHISPER_HOST=faster-whisper-server-cuda
      - WHISPER_PORT=8000
      - LIBRETRANSLATE_HOST=libretranslate-cuda
      - LIBRETRANSLATE_PORT=5000
      - FILTER_WEB_URL=https://gitee.com/voice-link-vr/VoiceLinkServer/raw/main/src/filter.json
      - THREADS_NUM=50
      - LIMIT_ENABLE=True
      - LIMIT_PUBLIC_TEST_USER=testuser
      - SQLALCHEMY_POOL_SIZE=30
      - SQLALCHEMY_MAX_OVERFLOW=60
volumes:
  voice-link-vr-server-local: